apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yml: |
    tunnel: 8ea0444f-8831-448f-9418-a2a973d5b15a
    credentials-file: /etc/cloudflared/credentials.json
    no-autoupdate: true
    ingress:
      - hostname: grafana.krymancer.dev
        service: http://kube-prom-grafana.monitoring.svc.cluster.local:80
      - hostname: argocd.krymancer.dev
        service: http://argocd-server.argocd.svc.cluster.local:80
      - service: http_status:404
