apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo-runner
data:
  config.yml: |
    log:
      level: info
    runner:
      file: .runner
      capacity: 2
      timeout: 3h
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
      labels:
        - "docker:docker://catthehacker/ubuntu:act-latest"
        - "ubuntu-latest:docker://catthehacker/ubuntu:act-latest"
    cache:
      enabled: true
      dir: ""
    container:
      network: ""
      privileged: false
      options: ""
      workdir_parent:
      valid_volumes:
        - /sock/docker.sock
      docker_host: "unix:///sock/docker.sock"
      force_pull: true
    host:
      workdir_parent:
