apiVersion: v1
kind: ConfigMap
metadata:
  name: homelable-nginx
  namespace: homelable
data:
  nginx.conf: "worker_processes 1;\npid /tmp/nginx.pid;\nerror_log /dev/stderr warn;\n\
    events { worker_connections 256; }\nhttp {\n  include /etc/nginx/mime.types;\n\
    \  default_type application/octet-stream;\n  access_log /dev/stdout;\n  client_body_temp_path\
    \ /tmp/client_temp;\n  proxy_temp_path /tmp/proxy_temp;\n  fastcgi_temp_path /tmp/fastcgi_temp;\n\
    \  uwsgi_temp_path /tmp/uwsgi_temp;\n  scgi_temp_path /tmp/scgi_temp;\n  map $http_upgrade\
    \ $connection_upgrade { default upgrade; '' close; }\n  server {\n    listen 8080;\n\
    \    server_name _;\n    root /usr/share/nginx/html;\n    index index.html;\n\
    \    client_max_body_size 32m;\n    location ~ ^/(api/|ws/) {\n      proxy_pass\
    \ http://127.0.0.1:8000;\n      proxy_http_version 1.1;\n      proxy_set_header\
    \ Upgrade $http_upgrade;\n      proxy_set_header Connection $connection_upgrade;\n\
    \      proxy_set_header Host $host;\n      proxy_set_header X-Real-IP $remote_addr;\n\
    \      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;\n      proxy_read_timeout\
    \ 3600s;\n    }\n    location / { try_files $uri $uri/ /index.html; }\n  }\n}\n"
