apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homelable-data
  namespace: homelable
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
