apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: actual
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
