apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-data
  namespace: termix
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
