apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cobalt
  namespace: cobalt
spec:
  tls:
    - hosts:
        - cobalt.homelab.krymancer.dev
        - cobalt-api.homelab.krymancer.dev
      secretName: homelab-wildcard-tls
  rules:
    - host: cobalt.homelab.krymancer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cobalt-web
                port:
                  number: 8080
    - host: cobalt-api.homelab.krymancer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cobalt
                port:
                  number: 9000
