apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: ntfy
  labels:
    app: ntfy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:latest
          args: ["serve"]
          env:
            - name: NTFY_BASE_URL
              value: "https://ntfy.homelab.krymancer.dev"
            - name: NTFY_BEHIND_PROXY
              value: "true"
            - name: NTFY_CACHE_FILE
              value: "/var/cache/ntfy/cache.db"
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: cache
              mountPath: /var/cache/ntfy
          resources:
            requests:
              memory: 32Mi
              cpu: 25m
            limits:
              memory: 128Mi
              cpu: 250m
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: ntfy-cache
